[config]
reload_apps = false

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.colors]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.cache/matugen/colors.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.mako]
input_path = "~/.config/matugen/templates/mako"
output_path = "~/.config/mako/mako-colors"
post_hook = "makoctl reload"

[templates.pywalfox]
input_path  = "~/.config/matugen/templates/pywalfox.json"
output_path = "~/.config/matugen/generated/pywalfox.json"
post_hook   = '''
bash -c '
{
  if command -v pywalfox >/dev/null 2>&1; then
    mkdir -p "$HOME/.cache/wal"
    ln -nfs "$HOME/.config/matugen/generated/pywalfox.json" "$HOME/.cache/wal/colors.json"
    pywalfox update
  fi
} >/dev/null 2>&1 </dev/null & disown
'
'''

[templates.rofi-colors]
input_path  = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.spotify]
input_path = '~/.config/matugen/templates/sleek.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.scss"
output_path = "~/.config/waybar/_colors.scss"

# [templates.wofi]
# input_path = "~/.config/matugen/templates/wofi.scss"
# output_path = "~/.config/wofi/colors.scss"