[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1a1111"
foreground = "#f0dedd"

[colors.normal]
black = "#140c0c"
red = "#690005"
green = "#e3c28c"
yellow = "#e6bdba"
blue = "#ffb3b0"
magenta = "#733333"
cyan = "#5d3f3e"
white = "#f0dedd"

[colors.bright]
black = "#3d3232"
red = "#ffdad6"
green = "#ffdeaa"
yellow = "#ffdad8"
blue = "#ffdad8"
magenta = "#ffb3b0"
cyan = "#e6bdba"
white = "#ffffff"
