[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0e1514"
foreground = "#dde4e2"

[colors.normal]
black = "#090f0f"
red = "#690005"
green = "#afc9e7"
yellow = "#b0ccc8"
blue = "#81d5cd"
magenta = "#00504b"
cyan = "#324b49"
white = "#dde4e2"

[colors.bright]
black = "#303635"
red = "#ffdad6"
green = "#cfe5ff"
yellow = "#cce8e4"
blue = "#9df2e9"
magenta = "#81d5cd"
cyan = "#b0ccc8"
white = "#ffffff"
