[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_background.default.hex}}"

[colors.normal]
black = "{{colors.surface_container_lowest.default.hex}}"
red = "{{colors.on_error.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
yellow = "{{colors.secondary.default.hex}}"
blue = "{{colors.primary.default.hex}}"
magenta = "{{colors.primary_container.default.hex}}"
cyan = "{{colors.secondary_container.default.hex}}"
white = "{{colors.on_surface.default.hex}}"

[colors.bright]
black = "{{colors.surface_container_highest.default.hex}}"
red = "{{colors.on_error_container.default.hex}}"
green = "{{colors.on_tertiary_container.default.hex}}"
yellow = "{{colors.on_secondary_container.default.hex}}"
blue = "{{colors.primary_fixed.default.hex}}"
magenta = "{{colors.primary_fixed_dim.default.hex}}"
cyan = "{{colors.secondary_fixed_dim.default.hex}}"
white = "#ffffff"
