$primary = rgba(f8b1ddff)
$on_primary = rgba(4f1e42ff)
$primary_container = rgba(6a3459ff)
$on_primary_container = rgba(ffd8edff)
$primary_fixed = rgba(ffd8edff)
$primary_fixed_dim = rgba(f8b1ddff)
$on_primary_fixed = rgba(36072bff)
$on_primary_fixed_variant = rgba(6a3459ff)

$secondary = rgba(ddbecfff)
$on_secondary = rgba(3f2a37ff)
$secondary_container = rgba(57404eff)
$on_secondary_container = rgba(fadaebff)
$secondary_fixed = rgba(fadaebff)
$secondary_fixed_dim = rgba(ddbecfff)
$on_secondary_fixed = rgba(281622ff)
$on_secondary_fixed_variant = rgba(57404eff)

$tertiary = rgba(f4b9a0ff)
$on_tertiary = rgba(4b2715ff)
$tertiary_container = rgba(653d29ff)
$on_tertiary_container = rgba(ffdbccff)
$tertiary_fixed = rgba(ffdbccff)
$tertiary_fixed_dim = rgba(f4b9a0ff)
$on_tertiary_fixed = rgba(321304ff)
$on_tertiary_fixed_variant = rgba(653d29ff)

$surface = rgba(181115ff)
$on_surface = rgba(eddfe4ff)
$surface_variant = rgba(4f444aff)
$on_surface_variant = rgba(d3c2caff)
$surface_container = rgba(251e21ff)
$surface_container_low = rgba(211a1dff)
$surface_container_high = rgba(2f282cff)
$surface_container_highest = rgba(3b3337ff)
$surface_container_lowest = rgba(130c10ff)
$surface_bright = rgba(3f373bff)
$surface_dim = rgba(181115ff)
$surface_tint = rgba(f8b1ddff)

$background = rgba(181115ff)
$on_background = rgba(eddfe4ff)

$error = rgba(ffb4abff)
$on_error = rgba(690005ff)
$error_container = rgba(93000aff)
$on_error_container = rgba(ffdad6ff)

$outline = rgba(9b8d94ff)
$outline_variant = rgba(4f444aff)

$inverse_primary = rgba(844b72ff)
$inverse_surface = rgba(eddfe4ff)
$inverse_on_surface = rgba(362e32ff)

$scrim = rgba(000000ff)
$shadow = rgba(000000ff)