$primary = rgba(ffb3b0ff)
$on_primary = rgba(571d1eff)
$primary_container = rgba(733333ff)
$on_primary_container = rgba(ffdad8ff)
$primary_fixed = rgba(ffdad8ff)
$primary_fixed_dim = rgba(ffb3b0ff)
$on_primary_fixed = rgba(3b080bff)
$on_primary_fixed_variant = rgba(733333ff)

$secondary = rgba(e6bdbaff)
$on_secondary = rgba(442928ff)
$secondary_container = rgba(5d3f3eff)
$on_secondary_container = rgba(ffdad8ff)
$secondary_fixed = rgba(ffdad8ff)
$secondary_fixed_dim = rgba(e6bdbaff)
$on_secondary_fixed = rgba(2c1514ff)
$on_secondary_fixed_variant = rgba(5d3f3eff)

$tertiary = rgba(e3c28cff)
$on_tertiary = rgba(412d05ff)
$tertiary_container = rgba(5a4319ff)
$on_tertiary_container = rgba(ffdeaaff)
$tertiary_fixed = rgba(ffdeaaff)
$tertiary_fixed_dim = rgba(e3c28cff)
$on_tertiary_fixed = rgba(271900ff)
$on_tertiary_fixed_variant = rgba(5a4319ff)

$surface = rgba(1a1111ff)
$on_surface = rgba(f0deddff)
$surface_variant = rgba(534342ff)
$on_surface_variant = rgba(d7c1c0ff)
$surface_container = rgba(271d1dff)
$surface_container_low = rgba(231919ff)
$surface_container_high = rgba(322827ff)
$surface_container_highest = rgba(3d3232ff)
$surface_container_lowest = rgba(140c0cff)
$surface_bright = rgba(423736ff)
$surface_dim = rgba(1a1111ff)
$surface_tint = rgba(ffb3b0ff)

$background = rgba(1a1111ff)
$on_background = rgba(f0deddff)

$error = rgba(ffb4abff)
$on_error = rgba(690005ff)
$error_container = rgba(93000aff)
$on_error_container = rgba(ffdad6ff)

$outline = rgba(a08c8bff)
$outline_variant = rgba(534342ff)

$inverse_primary = rgba(904a49ff)
$inverse_surface = rgba(f0deddff)
$inverse_on_surface = rgba(382e2dff)

$scrim = rgba(000000ff)
$shadow = rgba(000000ff)